puzzle_type: "cube_5/5/5"
model: "resnet"
model_args:
  state_dim: 150
  one_hot_depth: 6
  h1_dim: 512
  resnet_dim: 512
  num_resnet_blocks: 16
  out_dim: 1
  batch_norm: true
train_args:
  num_epochs: 20000
  batch_size: 256
  learning_rate: 0.001
  num_steps: 100
  save_increment: 1000
